# Generated by Django 5.2.8 on 2025-12-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="quantity",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Количество"
            ),
        ),
    ]
