# Generated by Django 5.2.8 on 2025-11-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=7, verbose_name="Скидка в %"
            ),
        ),
    ]
