# Generated by Django 5.2.8 on 2025-11-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=9, verbose_name="Скидка в %"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=9, verbose_name="Цена"
            ),
        ),
    ]
